export const resources = [
  {
    title: "Clozemaster",
    description:
      "Gamified language learning through mass exposure to vocabulary in context.",
    features: [""],
    languages: [
      "Spanish",
      "France",
      "Dutch",
      "Japanese",
      "Korean",
      "Italian",
      "Mandarin",
      "Portuguese",
      "Arabic",
      "Tagalog",
      "Swedish",
      "Turkish",
      "Norwegian",
      "Greek",
      "Latin",
      "Cantonese",
      "Persian",
      "Finnish",
      "Romanian",
      "Afrikaans",
      "Icelandic",
      "Danish",
      "Ukrainian",
      "Hindi",
      "Indonesian",
      "Hungarian",
      "Toki Pona",
      "Czech",
      "Croatian",
      "Irish",
      "Vietnamese",
      "Thai",
      "Welsh",
      "Catalan",
      "Serbian",
      "Bulgarian",
      "Scottish",
      "Estonian",
      "Slovak",
      "Yiddish",
      "Amharic",
      "Georgian",
      "Basque",
      "Latvian",
      "Albanian",
      "Breton",
      "Kazhk",
      "Armenian",
      "Interlingue",
      "Occitan",
      "Galician",
      "Macedonian",
      "Guarani",
      "Maori",
      "Bengali",
      "Belarusian",
      "Cornish",
      "Piedmontese",
      "Azerbaijani",
      "Lojban",
      "Swahili",
      "Nahuatl",
    ],
    types: ["Flashcards"],
    link: "https://www.clozemaster.com/dashboard",
    focus: "",
    cost: "",
  },
  {
    title: "Conversation Exchange",
    description:
      "Practice your goal language with natives for free through a language exchange.",
    features: ["Sorting by age, area, language and proficiency", ""],
    languages: ["All"],
    types: ["Language Exchange"],
    link: "https://www.conversationexchange.com/",
    focus: "",
    cost: "Free",
  },
  {
    title: "Duolingo",
    description:
      "An American educational technology company which produces learning apps and provides language certification",
    features: [""],
    languages: ["All"],
    types: ["Trivia Game"],
    link: "https://www.duolingo.com/learn",
    focus: "",
    cost: "",
  },
  {
    title: "Howtostudykorean",
    description:
      "The purpose of this website is to provide Korean learners with a one-stop resource for learning Korean. We strive to provide the most detailed, accurate and clear explanations at every step of the way – from learning how to read all the way to advanced grammar.",
    features: [""],
    languages: ["Korean"],
    types: ["Lessons"],
    link: "https://www.howtostudykorean.com/",
    focus: "",
    cost: "",
  },
  {
    title: "SpanishDict",
    description:
      "SpanishDict is a Spanish-English reference and learning website and mobile application. The website and mobile application feature a Spanish-English dictionary and translator, verb conjugation tables, pronunciation videos, and language lessons.",
    features: [""],
    languages: ["Spanish"],
    types: ["Translator"],
    link: "https://www.spanishdict.com/",
    focus: "",
    cost: "Free",
  },
  {
    title: "StudySpanish",
    description:
      "Learn Spanish with free online tutorials with audio, cultural notes, grammar, vocabulary, verbs drills, and links to helpful sites",
    features: [""],
    languages: ["Spanish"],
    types: ["Lessons"],
    link: "https://studyspanish.com/",
    focus: "",
    cost: "",
  },
  {
    title: "Coursera Korean",
    description:
      "This is an elementary-level Korean language course, consisting of 5 lessons with 4 units, and covers 4 skills: reading, writing, listening and speaking. ",
    features: [""],
    languages: ["Korean"],
    types: ["Lessons"],
    link: "https://www.coursera.org/learn/learn-korean",
    focus: "",
    cost: "Trial",
  },
  {
    title: "Korean Wiki ",
    description:
      "This project is a collaborative effort to unify knowledge on the Korean language and to make the information easily accessible and relevant to anyone.",
    features: [""],
    languages: ["Korean"],
    types: ["Lessons"],
    link: "https://www.koreanwikiproject.com/wiki/Main_Page",
    focus: "",
    cost: "Trial",
  },
  {
    title: "Korean Wiki - Hangeul",
    description:
      "A multitude of hangeul lessons and many examples with both male and female speakers. This is especially helpful for beginners.",
    features: [""],
    languages: ["Korean"],
    types: ["Lessons"],
    link: "https://www.koreanwikiproject.com/wiki/index.php?title=Learn_hangeul",
    focus: "",
    cost: "Trial",
  },
  {
    title: "Anki",
    description:
      "A free and open-source flashcard program using spaced repetition, a technique from cognitive science for memorization. ",
    features: ["Spaced repetition"],
    languages: ["All"],
    types: ["Lessons"],
    link: "https://apps.ankiweb.net/",
    focus: "",
    cost: "Depends",
    costDetails: "Free on laptops, but paid on IOS",
  },
  {
    title: "Reddit",
    description: "/languagelearning is a subreddit for language learners.",
    features: ["Connect with language learners across the globe"],
    languages: ["All"],
    types: ["Forum"],
    link: "https://www.reddit.com/r/languagelearning/",
    focus: "",
    cost: "Free",
    costDetails: "",
  },
  {
    title: "Heavenly Path",
    description:
      '"This guide is heavily focused on fiction reading and aimed at those with an interest in Chinese fiction and webnovels. If you are more interested in reading the news, business, scientific or other specific content then this may not be the right guide for you."',
    features: [""],
    languages: ["Mandarin"],
    types: ["Forum"],
    link: "https://heavenlypath.notion.site/Comprehensive-Reading-Guide-from-Beginner-to-Native-Novels-b3d6abd583a944a397b4fbbb81e0c38c",
    focus: "",
    cost: "Free",
    costDetails: "",
  },
  {
    title: "LexiLogos",
    description:
      "A multilingual keyboard that has a wide variety of languages.",
    features: [""],
    languages: ["All"],
    types: ["Keyboard"],
    link: "https://www.lexilogos.com/keyboard/index.htm",
    focus: "",
    cost: "Keyboard",
    costDetails: "",
  },
  {
    title: "Pinyin Pratice",
    description: "Practice tones",
    features: [""],
    languages: ["Mandarin"],
    types: ["Quiz"],
    link: "https://www.pinyinpractice.com/tones.htm",
    focus: "",
    cost: "",
    costDetails: "",
  },
  {
    title: "Yabla Mandarin",
    description: "Mandarin Chinese Pinyin Chart with Audio",
    features: [""],
    languages: ["Mandarin"],
    types: ["Reference"],
    link: "https://chinese.yabla.com/chinese-pinyin-chart.php",
    focus: "",
    cost: "",
    costDetails: "",
  },
  {
    title: "WordReference",
    description:
      "An online translation dictionary that supports Spanish, French, Italian, Portuguese, Catalan, Dutch, Polish, Romanian, etc.",
    features: [""],
    languages: [
      "Spanish",
      "French",
      "Dutch",
      "Russian",
      "Mandarin",
      "Korean",
      "Arabic",
    ],
    types: [""],
    link: "https://www.wordreference.com/",
    focus: "",
    cost: "Free",
    costDetails: "",
  },
  {
    title: "Almaany",
    description:
      "An Arabic dictionary with translations for English, Spanish, Portugues, French, Turkish, Indonesian and Dutch.",
    features: [""],
    languages: ["Arabic"],
    types: ["Dictionary"],
    link: "https://www.almaany.com/",
    focus: "",
    cost: "Free",
    costDetails: "",
  },
  {
    title: "Naver Spell Checker",
    description: "A Korean spell checker.",
    languages: ["Korean"],
    types: ["Spell checker"],
    link: "https://search.naver.com/search.naver?where=nexearch&sm=top_sly.hst&fbm=1&acr=1&ie=utf8&query=%EB%84%A4%EC%9D%B4%EB%B2%84+%EB%A7%9E%EC%B6%A4%EB%B2%95+%EA%B2%80%EC%82%AC%EA%B8%B0",
    focus: "Grammar",
    cost: "Free",
    costDetails: "",
  },
  {
    title: "Redlang",
    description: "Read websites in the language you're learning, translate words you don't know, and it'll create flashcards to help you remember.",
    languages: ["All"],
    types: ["Translator"],
    link: "https://readlang.com/",
    focus: "",
    cost: "Free",
    costDetails: "",
  },
  {
    title: "Podcast Addict",
    description: "An Android app that allows you to filter search results by multiple languages at once including Catalan, Korean, Russian, etc.",
    languages: ["All"],
    types: ["Podcasts"],
    link: "https://play.google.com/store/apps/details?id=com.bambuna.podcastaddict&hl=en",
    focus: "",
    cost: "",
    costDetails: "",
  },
  {
    title: "A language learners forum",
    description: "",
    languages: ["All"],
    types: ["Forum"],
    link: "https://forum.language-learners.org/",
    focus: "",
    cost: "Free",
    costDetails: "",
  },
  {
    title: "Forvo",
    description: "A pronunciation dictionary",
    languages: ["English", "Spanish", "French", "German", "Russian", "Japanese"],
    types: ["Dictionary"],
    link: "https://forvo.com/",
    focus: "",
    cost: "",
    costDetails: "",
  },
  {
    title: "Primary EBS",
    description: "It's like PBS kids but in Korean.",
    languages: ["Korean"],
    types: ["Lessons"],
    link: "https://primary.ebs.co.kr/main/primary",
    focus: "",
    cost: "",
    costDetails: "",
  },
  {
    title: "Language Transfer - Free",
    description: "Language Transfer Introduction and Complete audio courses capture real life learning experiences in which you can participate fully, wherever you are in the world!",
    languages: ["French", "Swahili", "Italian", "Greek", "German", "Turkish", "Arabic", "Spanish", "English"],
    types: ["Lessons"],
    link: "https://www.languagetransfer.org/free-courses-1",
    focus: "",
    cost: "",
    costDetails: "",
  },
  {
    title: "Language Course",
    description: "5000 word vocabulary builder.",
    languages: ["Arabic", "Mandarin", "Dutch","French","German","Hebrew","Hindi", "Italian", "Japanese", "Korean", "Russian", "Spanish", "Thai", "Turkish", "Vietnamese"],
    types: ["Flashcards"],
    link: "",
    focus: "",
    cost: "",
    costDetails: "",
  },
];

const template = [
  {
    title: "",
    description: "",
    languages: ["All"],
    types: [""],
    link: "",
    focus: "",
    cost: "",
    costDetails: "",
  },
];
